"""pr41_local_schema_baseline

Revision ID: 18a763bb049c
Revises:
Create Date: 2026-08-05 11:27:55.553480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '18a763bb049c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_webhook_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('event_id', sa.String(length=100), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'event_id', name='uq_payment_webhook_provider_event')
    )
    op.create_table('universities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_cn', sa.String(length=200), nullable=True),
    sa.Column('abbreviation', sa.String(length=50), nullable=True),
    sa.Column('aliases', postgresql.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=10), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_hot', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_universities_id'), 'universities', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('wechat_openid', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('wechat', sa.String(length=100), nullable=True),
    sa.Column('wechat_qr', sa.String(length=500), nullable=True),
    sa.Column('role', sa.Enum('tenant', 'landlord', 'maintenance_worker', 'admin', name='user_role'), nullable=False),
    sa.Column('status', sa.Enum('active', 'disabled', 'deleted', name='user_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_users_wechat_openid'), 'users', ['wechat_openid'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('details', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('active', 'closed', name='chat_session_status'), nullable=False),
    sa.Column('accumulated_filters', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_id'), 'chat_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_session_id'), 'chat_sessions', ['session_id'], unique=True)
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_table('compare_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('unit_type_ids', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('active', 'completed', name='compare_session_status'), nullable=False),
    sa.Column('result_cache', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compare_sessions_id'), 'compare_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_compare_sessions_user_id'), 'compare_sessions', ['user_id'], unique=False)
    op.create_table('data_imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.Enum('csv', 'excel', 'api', name='import_source_type'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='import_status'), nullable=False),
    sa.Column('total_records', sa.Integer(), nullable=False),
    sa.Column('success_records', sa.Integer(), nullable=False),
    sa.Column('failed_records', sa.Integer(), nullable=False),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_imports_admin_id'), 'data_imports', ['admin_id'], unique=False)
    op.create_index(op.f('ix_data_imports_id'), 'data_imports', ['id'], unique=False)
    op.create_table('institutes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.String(length=24), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_cn', sa.String(length=200), nullable=True),
    sa.Column('abbreviation', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('country', sa.String(length=10), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('street', sa.String(length=200), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('npc', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('contact_phone', sa.String(length=32), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('amenities', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('female_only', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('couples_allowed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('building_type', sa.String(length=50), nullable=True),
    sa.Column('total_floors', sa.Integer(), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('total_units', sa.Integer(), nullable=True),
    sa.Column('has_elevator', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('bm_id', sa.Integer(), nullable=True),
    sa.Column('bm_wechat', sa.String(length=100), nullable=True),
    sa.Column('bm_wechat_qr', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('has_api', sa.Boolean(), nullable=False),
    sa.Column('api_config', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('pending', 'active', 'suspended', name='institute_status'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bm_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_institutes_bm_id'), 'institutes', ['bm_id'], unique=False)
    op.create_index(op.f('ix_institutes_business_id'), 'institutes', ['business_id'], unique=True)
    op.create_index(op.f('ix_institutes_created_by'), 'institutes', ['created_by'], unique=False)
    op.create_index(op.f('ix_institutes_id'), 'institutes', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('booking_created', 'booking_approved', 'booking_rejected', 'booking_cancelled', 'booking_completed', 'payment_received', 'payment_created', 'payment_failed', 'payment_expired', 'contract_generated', 'contract_signed', 'auth_registration', 'auth_password_reset', 'repair_created', 'repair_assigned', 'repair_completed', 'repair_status_change', 'system', name='notification_type'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('entity_type', sa.String(length=40), nullable=True),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('order_id', sa.String(length=64), nullable=True),
    sa.Column('agreement_id', sa.String(length=100), nullable=True),
    sa.Column('unit_type_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index('ix_notifications_user_entity', 'notifications', ['user_id', 'entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_user_read_created', 'notifications', ['user_id', 'is_read', 'created_at'], unique=False)
    op.create_table('repair_workers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('available', 'working', 'on_leave', name='worker_status'), nullable=False),
    sa.Column('scope', sa.Enum('platform', 'apartment', name='worker_scope'), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('total_jobs', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repair_workers_id'), 'repair_workers', ['id'], unique=False)
    op.create_index(op.f('ix_repair_workers_manager_id'), 'repair_workers', ['manager_id'], unique=False)
    op.create_index(op.f('ix_repair_workers_user_id'), 'repair_workers', ['user_id'], unique=True)
    op.create_table('saved_searches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('query_params', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('notify_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_searches_id'), 'saved_searches', ['id'], unique=False)
    op.create_index(op.f('ix_saved_searches_user_id'), 'saved_searches', ['user_id'], unique=False)
    op.create_table('agent_carts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_carts_id'), 'agent_carts', ['id'], unique=False)
    op.create_index(op.f('ix_agent_carts_session_id'), 'agent_carts', ['session_id'], unique=False)
    op.create_index(op.f('ix_agent_carts_user_id'), 'agent_carts', ['user_id'], unique=False)
    op.create_table('apartment_visit_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('apartment_id', sa.Integer(), nullable=False),
    sa.Column('guest_phone', sa.String(length=32), nullable=False),
    sa.Column('guest_message', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['apartment_id'], ['institutes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apartment_visit_messages_apartment_id'), 'apartment_visit_messages', ['apartment_id'], unique=False)
    op.create_table('building_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institute_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=50), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institute_id'], ['institutes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename')
    )
    op.create_index(op.f('ix_building_images_id'), 'building_images', ['id'], unique=False)
    op.create_index(op.f('ix_building_images_institute_id'), 'building_images', ['institute_id'], unique=False)
    op.create_table('building_staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institute_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('wechat', sa.String(length=100), nullable=True),
    sa.Column('wechat_qr', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institute_id'], ['institutes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_building_staff_id'), 'building_staff', ['id'], unique=False)
    op.create_index(op.f('ix_building_staff_institute_id'), 'building_staff', ['institute_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', 'system', name='chat_message_role'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_table('compare_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('tool_calls', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['compare_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compare_messages_id'), 'compare_messages', ['id'], unique=False)
    op.create_index(op.f('ix_compare_messages_session_id'), 'compare_messages', ['session_id'], unique=False)
    op.create_table('contract_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('bm_id', sa.Integer(), nullable=False),
    sa.Column('institute_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('field_positions', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='字段坐标映射 {"tenant_name":{"page":1,"x":100,"y":200,"font_size":12}, ...}'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bm_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['institute_id'], ['institutes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_templates_bm_id'), 'contract_templates', ['bm_id'], unique=False)
    op.create_index(op.f('ix_contract_templates_institute_id'), 'contract_templates', ['institute_id'], unique=False)
    op.create_table('institute_commutes',
    sa.Column('institute_id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.Column('transit_min', sa.Integer(), nullable=True),
    sa.Column('walk_min', sa.Integer(), nullable=True),
    sa.Column('drive_min', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['institute_id'], ['institutes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('institute_id', 'university_id')
    )
    op.create_table('institute_pois',
    sa.Column('institute_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('poi_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed', sa.Boolean(), nullable=False),
    sa.Column('map_poi_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('safety_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institute_id'], ['institutes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('institute_id')
    )
    op.create_table('pms_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institute_id', sa.Integer(), nullable=False),
    sa.Column('pms_type', sa.Enum('starrez', 'mews', 'cloudbeds', 'ota_xml', 'custom', name='pms_type'), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False, comment="人工可读标签，如 'Unite Manchester'"),
    sa.Column('base_url', sa.String(length=500), nullable=False, comment='PMS API 地址，mock:// 前缀表示 Mock 模式'),
    sa.Column('api_key', sa.String(length=500), nullable=True, comment='PMS API Key（生产环境加密存储）'),
    sa.Column('webhook_secret', sa.String(length=200), nullable=True, comment='Webhook 验签密钥'),
    sa.Column('field_map_overrides', sa.JSON(), nullable=True, comment='入驻时 AI 辅助生成 + 人工确认后的个性化映射规则，合并到默认映射之上'),
    sa.Column('room_type_mapping', sa.JSON(), nullable=True, comment="房型名称 → 平台 PropertyType 的映射 { 'Ensuite Single': 'studio', ... }"),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sync_status', sa.Enum('idle', 'syncing', 'success', 'failed', 'pending_review', name='pms_sync_status'), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_error', sa.Text(), nullable=True),
    sa.Column('total_properties_synced', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institute_id'], ['institutes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pms_connections_id'), 'pms_connections', ['id'], unique=False)
    op.create_index(op.f('ix_pms_connections_institute_id'), 'pms_connections', ['institute_id'], unique=False)
    op.create_table('unit_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.String(length=24), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('institute_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('property_type', sa.String(length=50), nullable=True),
    sa.Column('bedrooms', sa.Integer(), nullable=False),
    sa.Column('bathrooms', sa.Integer(), nullable=False),
    sa.Column('hall_count', sa.Integer(), nullable=False),
    sa.Column('area_sqm', sa.Float(), nullable=True),
    sa.Column('base_rent', sa.Float(), nullable=False),
    sa.Column('deposit_amount', sa.Float(), nullable=True),
    sa.Column('deposit_type', sa.Enum('one_month', 'one_three', 'two_month', 'three_month', 'half_month', 'free', 'custom', name='unit_type_deposit_type'), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('lease_start', sa.String(length=50), nullable=True),
    sa.Column('lease_end', sa.String(length=50), nullable=True),
    sa.Column('lease_start_date', sa.Date(), nullable=True),
    sa.Column('lease_end_date', sa.Date(), nullable=True),
    sa.Column('special_offer', sa.Text(), nullable=True),
    sa.Column('floor_pricing', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_count', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('available_count', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('has_vacancy', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('amenities', postgresql.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('available_from', sa.Date(), nullable=True),
    sa.Column('min_stay_months', sa.Integer(), nullable=False),
    sa.Column('rental_requirements', sa.Text(), nullable=True),
    sa.Column('embedding', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('available', 'rented', 'maintenance', name='unit_type_status', create_constraint=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institute_id'], ['institutes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_unit_types_business_id'), 'unit_types', ['business_id'], unique=True)
    op.create_index(op.f('ix_unit_types_id'), 'unit_types', ['id'], unique=False)
    op.create_index(op.f('ix_unit_types_institute_id'), 'unit_types', ['institute_id'], unique=False)
    op.create_table('agent_cart_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('unit_type_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['agent_carts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_type_id'], ['unit_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cart_id', 'unit_type_id', name='uq_agent_cart_items_cart_unit_type')
    )
    op.create_index(op.f('ix_agent_cart_items_cart_id'), 'agent_cart_items', ['cart_id'], unique=False)
    op.create_index(op.f('ix_agent_cart_items_id'), 'agent_cart_items', ['id'], unique=False)
    op.create_index(op.f('ix_agent_cart_items_unit_type_id'), 'agent_cart_items', ['unit_type_id'], unique=False)
    op.create_table('embedding_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_type_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='embedding_job_status'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['unit_type_id'], ['unit_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_embedding_jobs_id'), 'embedding_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_embedding_jobs_unit_type_id'), 'embedding_jobs', ['unit_type_id'], unique=False)
    op.create_table('repair_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_type_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('bm_id', sa.Integer(), nullable=False),
    sa.Column('assigned_worker_id', sa.Integer(), nullable=True),
    sa.Column('issue_type', sa.Enum('plumbing', 'appliance', 'carpentry', 'wall_floor', 'plumbing_fixture', 'other', name='repair_issue_type'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'pending_escalated', 'assigned', 'in_progress', 'completed', 'confirmed', 'rejected', 'cancelled', name='repair_status'), nullable=False),
    sa.Column('scheduled_time', sa.String(length=32), nullable=True),
    sa.Column('completed_at', sa.String(length=32), nullable=True),
    sa.Column('work_record', sa.Text(), nullable=True),
    sa.Column('work_images', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_worker_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['bm_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_type_id'], ['unit_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repair_requests_assigned_worker_id'), 'repair_requests', ['assigned_worker_id'], unique=False)
    op.create_index(op.f('ix_repair_requests_bm_id'), 'repair_requests', ['bm_id'], unique=False)
    op.create_index(op.f('ix_repair_requests_id'), 'repair_requests', ['id'], unique=False)
    op.create_index(op.f('ix_repair_requests_status'), 'repair_requests', ['status'], unique=False)
    op.create_index(op.f('ix_repair_requests_tenant_id'), 'repair_requests', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_repair_requests_unit_type_id'), 'repair_requests', ['unit_type_id'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True, comment='租客标签'),
    sa.Column('chinese_name', sa.String(length=100), nullable=True),
    sa.Column('given_name_pinyin', sa.String(length=100), nullable=True),
    sa.Column('surname_pinyin', sa.String(length=100), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('school_name', sa.String(length=200), nullable=True),
    sa.Column('enrollment_grade', sa.String(length=100), nullable=True),
    sa.Column('major_english', sa.String(length=200), nullable=True),
    sa.Column('region', sa.String(length=200), nullable=True),
    sa.Column('address_detail', sa.String(length=500), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('emergency_chinese_name', sa.String(length=100), nullable=True),
    sa.Column('emergency_given_name_pinyin', sa.String(length=100), nullable=True),
    sa.Column('emergency_surname_pinyin', sa.String(length=100), nullable=True),
    sa.Column('emergency_relation', sa.String(length=50), nullable=True),
    sa.Column('emergency_birth_date', sa.Date(), nullable=True),
    sa.Column('emergency_phone', sa.String(length=32), nullable=True),
    sa.Column('emergency_email', sa.String(length=255), nullable=True),
    sa.Column('emergency_gender', sa.String(length=20), nullable=True),
    sa.Column('emergency_region', sa.String(length=200), nullable=True),
    sa.Column('emergency_address_detail', sa.String(length=500), nullable=True),
    sa.Column('emergency_postal_code', sa.String(length=20), nullable=True),
    sa.Column('emergency_consultant_id', sa.String(length=50), nullable=True),
    sa.Column('current_unit_type_id', sa.Integer(), nullable=True),
    sa.Column('room_number', sa.String(length=50), nullable=True, comment='房间号'),
    sa.Column('housing_status', sa.String(length=20), nullable=True),
    sa.Column('move_in_date', sa.Date(), nullable=True),
    sa.Column('move_out_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['current_unit_type_id'], ['unit_types.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_current_unit_type_id'), 'tenants', ['current_unit_type_id'], unique=False)
    op.create_index(op.f('ix_tenants_user_id'), 'tenants', ['user_id'], unique=False)
    op.create_table('unit_type_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_type_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=50), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['unit_type_id'], ['unit_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename')
    )
    op.create_index(op.f('ix_unit_type_images_id'), 'unit_type_images', ['id'], unique=False)
    op.create_index(op.f('ix_unit_type_images_unit_type_id'), 'unit_type_images', ['unit_type_id'], unique=False)
    op.create_table('user_favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('unit_type_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['unit_type_id'], ['unit_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'unit_type_id', name='uq_user_favorite_unit_type')
    )
    op.create_index(op.f('ix_user_favorites_id'), 'user_favorites', ['id'], unique=False)
    op.create_index(op.f('ix_user_favorites_unit_type_id'), 'user_favorites', ['unit_type_id'], unique=False)
    op.create_index(op.f('ix_user_favorites_user_id'), 'user_favorites', ['user_id'], unique=False)
    op.create_table('booking_flow_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('unit_type_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('current_step', sa.String(length=32), nullable=False),
    sa.Column('move_in_date', sa.String(length=32), nullable=True),
    sa.Column('lease_months', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['unit_type_id'], ['unit_types.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_flow_drafts_id'), 'booking_flow_drafts', ['id'], unique=False)
    op.create_index(op.f('ix_booking_flow_drafts_tenant_id'), 'booking_flow_drafts', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_booking_flow_drafts_unit_type_id'), 'booking_flow_drafts', ['unit_type_id'], unique=False)
    op.create_index(op.f('ix_booking_flow_drafts_user_id'), 'booking_flow_drafts', ['user_id'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('unit_type_id', sa.Integer(), nullable=True),
    sa.Column('institute_id', sa.Integer(), nullable=True),
    sa.Column('bm_id', sa.Integer(), nullable=True),
    sa.Column('room_number', sa.String(length=20), nullable=True, comment='BM填的房号'),
    sa.Column('scheduled_date', sa.String(length=32), nullable=True, comment='预计入住日'),
    sa.Column('contract_start', sa.Date(), nullable=True, comment='合同开始日'),
    sa.Column('contract_end', sa.Date(), nullable=True, comment='合同结束日'),
    sa.Column('lease_months', sa.Integer(), nullable=True),
    sa.Column('deposit_amount', sa.Integer(), nullable=True),
    sa.Column('service_fee', sa.Integer(), nullable=True),
    sa.Column('total_rent', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'cancelled', 'completed', 'contract_ready', 'contract_signed', 'payment_pending', 'payment_processing', 'paid', 'payment_failed', 'payment_expired', 'refund_pending', 'refunded', 'payment_review', name='booking_status'), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('deposit_status', sa.String(length=20), nullable=False),
    sa.Column('payment_transaction_id', sa.String(length=255), nullable=True),
    sa.Column('payment_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('inventory_reserved', sa.Boolean(), nullable=False),
    sa.Column('application_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='{pricing_snapshot}'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bm_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['institute_id'], ['institutes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['unit_type_id'], ['unit_types.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_bm_id'), 'bookings', ['bm_id'], unique=False)
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
    op.create_index(op.f('ix_bookings_institute_id'), 'bookings', ['institute_id'], unique=False)
    op.create_index(op.f('ix_bookings_tenant_id'), 'bookings', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_bookings_unit_type_id'), 'bookings', ['unit_type_id'], unique=False)
    op.create_index(op.f('ix_bookings_user_id'), 'bookings', ['user_id'], unique=False)
    op.create_table('contracts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('unit_type_id', sa.Integer(), nullable=True),
    sa.Column('template_name', sa.String(length=100), nullable=False),
    sa.Column('agreement_number', sa.String(length=64), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('template_version', sa.String(length=32), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('pdf_status', sa.String(length=20), nullable=False),
    sa.Column('pdf_last_error', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_type_id'], ['unit_types.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id', 'version', name='uq_contracts_booking_version')
    )
    op.create_index(op.f('ix_contracts_agreement_number'), 'contracts', ['agreement_number'], unique=True)
    op.create_index(op.f('ix_contracts_booking_id'), 'contracts', ['booking_id'], unique=False)
    op.create_index(op.f('ix_contracts_content_hash'), 'contracts', ['content_hash'], unique=False)
    op.create_index(op.f('ix_contracts_tenant_id'), 'contracts', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_contracts_unit_type_id'), 'contracts', ['unit_type_id'], unique=False)
    op.create_table('notification_outbox',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_key', sa.String(length=180), nullable=False),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('template_version', sa.String(length=20), nullable=False),
    sa.Column('recipient_email', sa.String(length=255), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'sent', 'failed', name='notification_outbox_status'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('retryable', sa.Boolean(), nullable=False),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_outbox_booking_id'), 'notification_outbox', ['booking_id'], unique=False)
    op.create_index(op.f('ix_notification_outbox_event_key'), 'notification_outbox', ['event_key'], unique=True)
    op.create_index(op.f('ix_notification_outbox_event_type'), 'notification_outbox', ['event_type'], unique=False)
    op.create_index(op.f('ix_notification_outbox_next_attempt_at'), 'notification_outbox', ['next_attempt_at'], unique=False)
    op.create_index(op.f('ix_notification_outbox_status'), 'notification_outbox', ['status'], unique=False)
    op.create_index(op.f('ix_notification_outbox_user_id'), 'notification_outbox', ['user_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=False),
    sa.Column('payment_attempt_id', sa.String(length=64), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('out_trade_no', sa.String(length=255), nullable=True),
    sa.Column('transaction_id', sa.String(length=255), nullable=True),
    sa.Column('trade_state', sa.String(length=50), nullable=True),
    sa.Column('trade_state_desc', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'success', 'failed', 'closed', 'expired', 'review', 'refund_pending', 'refunded', name='payment_status'), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settlement_currency', sa.String(length=3), nullable=False),
    sa.Column('settlement_amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('cny_reference_amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('property_currency', sa.String(length=3), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=24, scale=12), nullable=False),
    sa.Column('exchange_rate_source', sa.String(length=200), nullable=False),
    sa.Column('exchange_rate_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('provider_payment_id', sa.String(length=100), nullable=True),
    sa.Column('provider_checkout_id', sa.String(length=100), nullable=True),
    sa.Column('provider_merchant_account', sa.String(length=100), nullable=True),
    sa.Column('checkout_url', sa.String(length=500), nullable=True),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key'),
    sa.UniqueConstraint('provider_checkout_id'),
    sa.UniqueConstraint('provider_payment_id')
    )
    op.create_index(op.f('ix_payments_booking_id'), 'payments', ['booking_id'], unique=False)
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=True)
    op.create_index(op.f('ix_payments_payment_attempt_id'), 'payments', ['payment_attempt_id'], unique=True)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.create_table('policy_consents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('policy_key', sa.String(length=64), nullable=False),
    sa.Column('policy_version', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_consents_booking_id'), 'policy_consents', ['booking_id'], unique=False)
    op.create_index(op.f('ix_policy_consents_id'), 'policy_consents', ['id'], unique=False)
    op.create_index(op.f('ix_policy_consents_user_id'), 'policy_consents', ['user_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('institute_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='review_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['institute_id'], ['institutes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_booking_id'), 'reviews', ['booking_id'], unique=True)
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    op.create_index(op.f('ix_reviews_institute_id'), 'reviews', ['institute_id'], unique=False)
    op.create_index(op.f('ix_reviews_tenant_id'), 'reviews', ['tenant_id'], unique=False)
    op.create_table('contract_signatures',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agreement_id', sa.String(length=36), nullable=False),
    sa.Column('agreement_version', sa.Integer(), nullable=False),
    sa.Column('agreement_content_hash', sa.String(length=64), nullable=False),
    sa.Column('tenant_user_id', sa.Integer(), nullable=False),
    sa.Column('tenant_name', sa.String(length=200), nullable=False),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('property_timezone', sa.String(length=64), nullable=False),
    sa.Column('consent_text_version', sa.String(length=32), nullable=False),
    sa.Column('signature_object_key', sa.String(length=500), nullable=False),
    sa.Column('signature_hash', sa.String(length=64), nullable=False),
    sa.Column('signed_pdf_object_key', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agreement_id'], ['contracts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_contract_signatures_agreement_id'), 'contract_signatures', ['agreement_id'], unique=True)
    op.create_index(op.f('ix_contract_signatures_tenant_user_id'), 'contract_signatures', ['tenant_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contract_signatures_tenant_user_id'), table_name='contract_signatures')
    op.drop_index(op.f('ix_contract_signatures_agreement_id'), table_name='contract_signatures')
    op.drop_table('contract_signatures')
    op.drop_index(op.f('ix_reviews_tenant_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_institute_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_booking_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_policy_consents_user_id'), table_name='policy_consents')
    op.drop_index(op.f('ix_policy_consents_id'), table_name='policy_consents')
    op.drop_index(op.f('ix_policy_consents_booking_id'), table_name='policy_consents')
    op.drop_table('policy_consents')
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_attempt_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_booking_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_notification_outbox_user_id'), table_name='notification_outbox')
    op.drop_index(op.f('ix_notification_outbox_status'), table_name='notification_outbox')
    op.drop_index(op.f('ix_notification_outbox_next_attempt_at'), table_name='notification_outbox')
    op.drop_index(op.f('ix_notification_outbox_event_type'), table_name='notification_outbox')
    op.drop_index(op.f('ix_notification_outbox_event_key'), table_name='notification_outbox')
    op.drop_index(op.f('ix_notification_outbox_booking_id'), table_name='notification_outbox')
    op.drop_table('notification_outbox')
    op.drop_index(op.f('ix_contracts_unit_type_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_tenant_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_content_hash'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_booking_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_agreement_number'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_index(op.f('ix_bookings_user_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_unit_type_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_tenant_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_institute_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_bm_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_booking_flow_drafts_user_id'), table_name='booking_flow_drafts')
    op.drop_index(op.f('ix_booking_flow_drafts_unit_type_id'), table_name='booking_flow_drafts')
    op.drop_index(op.f('ix_booking_flow_drafts_tenant_id'), table_name='booking_flow_drafts')
    op.drop_index(op.f('ix_booking_flow_drafts_id'), table_name='booking_flow_drafts')
    op.drop_table('booking_flow_drafts')
    op.drop_index(op.f('ix_user_favorites_user_id'), table_name='user_favorites')
    op.drop_index(op.f('ix_user_favorites_unit_type_id'), table_name='user_favorites')
    op.drop_index(op.f('ix_user_favorites_id'), table_name='user_favorites')
    op.drop_table('user_favorites')
    op.drop_index(op.f('ix_unit_type_images_unit_type_id'), table_name='unit_type_images')
    op.drop_index(op.f('ix_unit_type_images_id'), table_name='unit_type_images')
    op.drop_table('unit_type_images')
    op.drop_index(op.f('ix_tenants_user_id'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_current_unit_type_id'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_repair_requests_unit_type_id'), table_name='repair_requests')
    op.drop_index(op.f('ix_repair_requests_tenant_id'), table_name='repair_requests')
    op.drop_index(op.f('ix_repair_requests_status'), table_name='repair_requests')
    op.drop_index(op.f('ix_repair_requests_id'), table_name='repair_requests')
    op.drop_index(op.f('ix_repair_requests_bm_id'), table_name='repair_requests')
    op.drop_index(op.f('ix_repair_requests_assigned_worker_id'), table_name='repair_requests')
    op.drop_table('repair_requests')
    op.drop_index(op.f('ix_embedding_jobs_unit_type_id'), table_name='embedding_jobs')
    op.drop_index(op.f('ix_embedding_jobs_id'), table_name='embedding_jobs')
    op.drop_table('embedding_jobs')
    op.drop_index(op.f('ix_agent_cart_items_unit_type_id'), table_name='agent_cart_items')
    op.drop_index(op.f('ix_agent_cart_items_id'), table_name='agent_cart_items')
    op.drop_index(op.f('ix_agent_cart_items_cart_id'), table_name='agent_cart_items')
    op.drop_table('agent_cart_items')
    op.drop_index(op.f('ix_unit_types_institute_id'), table_name='unit_types')
    op.drop_index(op.f('ix_unit_types_id'), table_name='unit_types')
    op.drop_index(op.f('ix_unit_types_business_id'), table_name='unit_types')
    op.drop_table('unit_types')
    op.drop_index(op.f('ix_pms_connections_institute_id'), table_name='pms_connections')
    op.drop_index(op.f('ix_pms_connections_id'), table_name='pms_connections')
    op.drop_table('pms_connections')
    op.drop_table('institute_pois')
    op.drop_table('institute_commutes')
    op.drop_index(op.f('ix_contract_templates_institute_id'), table_name='contract_templates')
    op.drop_index(op.f('ix_contract_templates_bm_id'), table_name='contract_templates')
    op.drop_table('contract_templates')
    op.drop_index(op.f('ix_compare_messages_session_id'), table_name='compare_messages')
    op.drop_index(op.f('ix_compare_messages_id'), table_name='compare_messages')
    op.drop_table('compare_messages')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_building_staff_institute_id'), table_name='building_staff')
    op.drop_index(op.f('ix_building_staff_id'), table_name='building_staff')
    op.drop_table('building_staff')
    op.drop_index(op.f('ix_building_images_institute_id'), table_name='building_images')
    op.drop_index(op.f('ix_building_images_id'), table_name='building_images')
    op.drop_table('building_images')
    op.drop_index(op.f('ix_apartment_visit_messages_apartment_id'), table_name='apartment_visit_messages')
    op.drop_table('apartment_visit_messages')
    op.drop_index(op.f('ix_agent_carts_user_id'), table_name='agent_carts')
    op.drop_index(op.f('ix_agent_carts_session_id'), table_name='agent_carts')
    op.drop_index(op.f('ix_agent_carts_id'), table_name='agent_carts')
    op.drop_table('agent_carts')
    op.drop_index(op.f('ix_saved_searches_user_id'), table_name='saved_searches')
    op.drop_index(op.f('ix_saved_searches_id'), table_name='saved_searches')
    op.drop_table('saved_searches')
    op.drop_index(op.f('ix_repair_workers_user_id'), table_name='repair_workers')
    op.drop_index(op.f('ix_repair_workers_manager_id'), table_name='repair_workers')
    op.drop_index(op.f('ix_repair_workers_id'), table_name='repair_workers')
    op.drop_table('repair_workers')
    op.drop_index('ix_notifications_user_read_created', table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index('ix_notifications_user_entity', table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_institutes_id'), table_name='institutes')
    op.drop_index(op.f('ix_institutes_created_by'), table_name='institutes')
    op.drop_index(op.f('ix_institutes_business_id'), table_name='institutes')
    op.drop_index(op.f('ix_institutes_bm_id'), table_name='institutes')
    op.drop_table('institutes')
    op.drop_index(op.f('ix_data_imports_id'), table_name='data_imports')
    op.drop_index(op.f('ix_data_imports_admin_id'), table_name='data_imports')
    op.drop_table('data_imports')
    op.drop_index(op.f('ix_compare_sessions_user_id'), table_name='compare_sessions')
    op.drop_index(op.f('ix_compare_sessions_id'), table_name='compare_sessions')
    op.drop_table('compare_sessions')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_session_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_wechat_openid'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_universities_id'), table_name='universities')
    op.drop_table('universities')
    op.drop_table('payment_webhook_events')
    # ### end Alembic commands ###
