"""add_safety_data_to_property_pois

Revision ID: 1dae7a92bd3f
Revises: e5f6a7b8c9d0
Create Date: 2026-07-22 19:14:12.402713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '1dae7a92bd3f'
down_revision: Union[str, None] = 'e5f6a7b8c9d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('id_number', sa.String(length=50), nullable=True),
    sa.Column('emergency_contact', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('building_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institute_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=50), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institute_id'], ['institutes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename')
    )
    op.create_index(op.f('ix_building_images_id'), 'building_images', ['id'], unique=False)
    op.create_index(op.f('ix_building_images_institute_id'), 'building_images', ['institute_id'], unique=False)
    op.create_table('building_staff',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('institute_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institute_id'], ['institutes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_building_staff_institute_id'), 'building_staff', ['institute_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('deposit_status', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['properties.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_room_id'), 'orders', ['room_id'], unique=False)
    op.create_index(op.f('ix_orders_tenant_id'), 'orders', ['tenant_id'], unique=False)
    op.create_table('room_transfers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.String(length=30), nullable=True),
    sa.Column('to_status', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_transfers_room_id'), 'room_transfers', ['room_id'], unique=False)
    op.drop_index('ix_compare_messages_id', table_name='compare_messages')
    op.drop_index('ix_compare_messages_session_id', table_name='compare_messages')
    op.drop_table('compare_messages')
    op.drop_index('ix_compare_sessions_id', table_name='compare_sessions')
    op.drop_index('ix_compare_sessions_user_id', table_name='compare_sessions')
    op.drop_table('compare_sessions')
    op.add_column('bookings', sa.Column('lease_months', sa.Integer(), nullable=True))
    op.add_column('bookings', sa.Column('total_rent', sa.Integer(), nullable=True))
    op.add_column('bookings', sa.Column('application_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('chat_sessions', sa.Column('accumulated_filters', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.alter_column('chat_sessions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('contracts_booking_id_key', 'contracts', type_='unique')
    op.drop_index('ix_contracts_id', table_name='contracts')
    op.drop_index('ix_contracts_booking_id', table_name='contracts')
    op.create_index(op.f('ix_contracts_booking_id'), 'contracts', ['booking_id'], unique=True)
    op.alter_column('institutes', 'amenities',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.ARRAY(sa.String(length=50)),
               existing_nullable=True)
    op.alter_column('institutes', 'female_only',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('institutes', 'couples_allowed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.create_index(op.f('ix_institutes_business_id'), 'institutes', ['business_id'], unique=True)
    op.add_column('payments', sa.Column('out_trade_no', sa.String(length=255), nullable=True))
    op.add_column('payments', sa.Column('trade_state', sa.String(length=50), nullable=True))
    op.add_column('payments', sa.Column('trade_state_desc', sa.String(length=255), nullable=True))
    op.alter_column('payments', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('pending', 'processing', 'success', 'failed', 'closed', name='payment_status'),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_index('ix_payments_id', table_name='payments')
    op.alter_column('pms_connections', 'label',
               existing_type=sa.VARCHAR(length=100),
               comment="人工可读标签，如 'Unite Manchester'",
               existing_nullable=False)
    op.alter_column('pms_connections', 'base_url',
               existing_type=sa.VARCHAR(length=500),
               comment='PMS API 地址，mock:// 前缀表示 Mock 模式',
               existing_nullable=False)
    op.alter_column('pms_connections', 'api_key',
               existing_type=sa.VARCHAR(length=500),
               comment='PMS API Key（生产环境加密存储）',
               existing_nullable=True)
    op.alter_column('pms_connections', 'webhook_secret',
               existing_type=sa.VARCHAR(length=200),
               comment='Webhook 验签密钥',
               existing_nullable=True)
    op.alter_column('pms_connections', 'field_map_overrides',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='入驻时 AI 辅助生成 + 人工确认后的个性化映射规则，合并到默认映射之上',
               existing_nullable=True)
    op.alter_column('pms_connections', 'room_type_mapping',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment="房型名称 → 平台 PropertyType 的映射 { 'Ensuite Single': 'studio', ... }",
               existing_nullable=True)
    op.alter_column('properties', 'title',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('properties', 'address',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=500),
               nullable=True)
    op.alter_column('properties', 'district',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('properties', 'price_monthly',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('properties', 'bedrooms',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('properties', 'bathrooms',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('properties', 'property_type',
               existing_type=postgresql.ENUM('apartment', 'house', 'studio', 'shared', name='property_type'),
               type_=sa.String(length=50),
               nullable=True)
    op.alter_column('properties', 'deposit_type',
               existing_type=postgresql.ENUM('one_month', 'one_three', 'two_month', 'three_month', 'half_month', 'free', 'custom', name='deposit_type'),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('properties', 'country',
               existing_type=sa.VARCHAR(length=2),
               type_=sa.String(length=100),
               nullable=True,
               existing_server_default=sa.text("'CN'::character varying"))
    op.alter_column('properties', 'rent_type',
               existing_type=postgresql.ENUM('monthly', 'quarterly', 'yearly', name='rent_type'),
               type_=sa.String(length=50),
               nullable=True,
               existing_server_default=sa.text("'monthly'::rent_type"))
    op.alter_column('properties', 'rental_rules',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('properties', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('properties', 'min_stay_months',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('3'))
    op.alter_column('properties', 'min_lease_months',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('12'))
    op.drop_index('ix_properties_country', table_name='properties')
    op.drop_index('ix_properties_district', table_name='properties')
    op.drop_index('ix_properties_district_status', table_name='properties')
    op.drop_index('ix_properties_embedding_ivfflat', table_name='properties', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_index(op.f('ix_properties_unit_type_id'), 'properties', ['unit_type_id'], unique=False)
    op.drop_constraint('fk_properties_institute_id_institutes', 'properties', type_='foreignkey')
    op.create_foreign_key(None, 'properties', 'room_types', ['unit_type_id'], ['id'], ondelete='SET NULL')
    op.drop_column('properties', 'amenities')
    op.drop_column('properties', 'city')
    op.drop_column('properties', 'special_discount')
    op.drop_column('properties', 'building_block')
    op.add_column('property_pois', sa.Column('safety_data', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.drop_index('ix_property_pois_id', table_name='property_pois')
    op.drop_constraint('property_pois_property_id_key', 'property_pois', type_='unique')
    op.drop_index('ix_property_pois_property_id', table_name='property_pois')
    op.create_index(op.f('ix_property_pois_property_id'), 'property_pois', ['property_id'], unique=True)
    op.alter_column('reviews', 'booking_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('reviews_booking_id_key', 'reviews', type_='unique')
    op.drop_index('ix_reviews_booking_id', table_name='reviews')
    op.create_index(op.f('ix_reviews_booking_id'), 'reviews', ['booking_id'], unique=True)
    op.alter_column('room_types', 'property_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('room_types', 'room_type',
               existing_type=postgresql.ENUM('studio', 'ensuite', '1bed', '2bed', '3bed+', 'shared', 'one_bed', 'two_bed', 'three_bed_plus', name='room_type_enum'),
               nullable=True)
    op.alter_column('room_types', 'bedrooms',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('room_types', 'bathrooms',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('room_types', 'price_monthly',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('room_types', 'available_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('room_types', 'amenities',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=30)),
               type_=postgresql.ARRAY(sa.String(length=50)),
               existing_nullable=True)
    op.alter_column('room_types', 'min_stay_months',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('3'))
    op.alter_column('room_types', 'status',
               existing_type=postgresql.ENUM('available', 'rented', 'maintenance', name='room_type_status'),
               nullable=True,
               existing_server_default=sa.text("'available'::room_type_status"))
    op.drop_constraint('room_types_property_id_fkey', 'room_types', type_='foreignkey')
    op.alter_column('user_favorites', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user_favorites', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('user_favorites', 'property_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.create_index(op.f('ix_user_favorites_id'), 'user_favorites', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_favorites_id'), table_name='user_favorites')
    op.alter_column('user_favorites', 'property_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('user_favorites', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('user_favorites', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.create_foreign_key('room_types_property_id_fkey', 'room_types', 'properties', ['property_id'], ['id'], ondelete='CASCADE')
    op.alter_column('room_types', 'status',
               existing_type=postgresql.ENUM('available', 'rented', 'maintenance', name='room_type_status'),
               nullable=False,
               existing_server_default=sa.text("'available'::room_type_status"))
    op.alter_column('room_types', 'min_stay_months',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('3'))
    op.alter_column('room_types', 'amenities',
               existing_type=postgresql.ARRAY(sa.String(length=50)),
               type_=postgresql.ARRAY(sa.VARCHAR(length=30)),
               existing_nullable=True)
    op.alter_column('room_types', 'available_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('room_types', 'price_monthly',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('room_types', 'bathrooms',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('room_types', 'bedrooms',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('room_types', 'room_type',
               existing_type=postgresql.ENUM('studio', 'ensuite', '1bed', '2bed', '3bed+', 'shared', 'one_bed', 'two_bed', 'three_bed_plus', name='room_type_enum'),
               nullable=False)
    op.alter_column('room_types', 'property_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_reviews_booking_id'), table_name='reviews')
    op.create_index('ix_reviews_booking_id', 'reviews', ['booking_id'], unique=False)
    op.create_unique_constraint('reviews_booking_id_key', 'reviews', ['booking_id'])
    op.alter_column('reviews', 'booking_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_property_pois_property_id'), table_name='property_pois')
    op.create_index('ix_property_pois_property_id', 'property_pois', ['property_id'], unique=False)
    op.create_unique_constraint('property_pois_property_id_key', 'property_pois', ['property_id'])
    op.create_index('ix_property_pois_id', 'property_pois', ['id'], unique=False)
    op.drop_column('property_pois', 'safety_data')
    op.add_column('properties', sa.Column('building_block', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('properties', sa.Column('special_discount', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('properties', sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('properties', sa.Column('amenities', postgresql.ARRAY(sa.VARCHAR(length=30)), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'properties', type_='foreignkey')
    op.create_foreign_key('fk_properties_institute_id_institutes', 'properties', 'institutes', ['institute_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_properties_unit_type_id'), table_name='properties')
    op.create_index('ix_properties_embedding_ivfflat', 'properties', ['embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_index('ix_properties_district_status', 'properties', ['district', 'status'], unique=False)
    op.create_index('ix_properties_district', 'properties', ['district'], unique=False)
    op.create_index('ix_properties_country', 'properties', ['country'], unique=False)
    op.alter_column('properties', 'min_lease_months',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('12'))
    op.alter_column('properties', 'min_stay_months',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('3'))
    op.alter_column('properties', 'embedding',
               existing_type=sa.Text(),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               existing_nullable=True)
    op.alter_column('properties', 'rental_rules',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('properties', 'rent_type',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('monthly', 'quarterly', 'yearly', name='rent_type'),
               nullable=False,
               existing_server_default=sa.text("'monthly'::rent_type"))
    op.alter_column('properties', 'country',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=2),
               nullable=False,
               existing_server_default=sa.text("'CN'::character varying"))
    op.alter_column('properties', 'deposit_type',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('one_month', 'one_three', 'two_month', 'three_month', 'half_month', 'free', 'custom', name='deposit_type'),
               existing_nullable=True)
    op.alter_column('properties', 'property_type',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('apartment', 'house', 'studio', 'shared', name='property_type'),
               nullable=False)
    op.alter_column('properties', 'bathrooms',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('properties', 'bedrooms',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('properties', 'price_monthly',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('properties', 'district',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('properties', 'address',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=300),
               nullable=False)
    op.alter_column('properties', 'title',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('pms_connections', 'room_type_mapping',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment="房型名称 → 平台 PropertyType 的映射 { 'Ensuite Single': 'studio', ... }",
               existing_nullable=True)
    op.alter_column('pms_connections', 'field_map_overrides',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='入驻时 AI 辅助生成 + 人工确认后的个性化映射规则，合并到默认映射之上',
               existing_nullable=True)
    op.alter_column('pms_connections', 'webhook_secret',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='Webhook 验签密钥',
               existing_nullable=True)
    op.alter_column('pms_connections', 'api_key',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='PMS API Key（生产环境加密存储）',
               existing_nullable=True)
    op.alter_column('pms_connections', 'base_url',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='PMS API 地址，mock:// 前缀表示 Mock 模式',
               existing_nullable=False)
    op.alter_column('pms_connections', 'label',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment="人工可读标签，如 'Unite Manchester'",
               existing_nullable=False)
    op.create_index('ix_payments_id', 'payments', ['id'], unique=False)
    op.alter_column('payments', 'status',
               existing_type=sa.Enum('pending', 'processing', 'success', 'failed', 'closed', name='payment_status'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_column('payments', 'trade_state_desc')
    op.drop_column('payments', 'trade_state')
    op.drop_column('payments', 'out_trade_no')
    op.drop_index(op.f('ix_institutes_business_id'), table_name='institutes')
    op.alter_column('institutes', 'couples_allowed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('institutes', 'female_only',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('institutes', 'amenities',
               existing_type=postgresql.ARRAY(sa.String(length=50)),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_contracts_booking_id'), table_name='contracts')
    op.create_index('ix_contracts_booking_id', 'contracts', ['booking_id'], unique=False)
    op.create_index('ix_contracts_id', 'contracts', ['id'], unique=False)
    op.create_unique_constraint('contracts_booking_id_key', 'contracts', ['booking_id'])
    op.alter_column('chat_sessions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('chat_sessions', 'accumulated_filters')
    op.drop_column('bookings', 'application_data')
    op.drop_column('bookings', 'total_rent')
    op.drop_column('bookings', 'lease_months')
    op.create_table('compare_sessions',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('compare_sessions_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('property_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('priority', sa.VARCHAR(length=20), server_default=sa.text("'balanced'::character varying"), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('active', 'completed', name='compare_session_status'), server_default=sa.text("'active'::compare_session_status"), autoincrement=False, nullable=False),
    sa.Column('result_cache', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='compare_sessions_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='compare_sessions_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_compare_sessions_user_id', 'compare_sessions', ['user_id'], unique=False)
    op.create_index('ix_compare_sessions_id', 'compare_sessions', ['id'], unique=False)
    op.create_table('compare_messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tool_calls', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['compare_sessions.id'], name='compare_messages_session_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='compare_messages_pkey')
    )
    op.create_index('ix_compare_messages_session_id', 'compare_messages', ['session_id'], unique=False)
    op.create_index('ix_compare_messages_id', 'compare_messages', ['id'], unique=False)
    op.drop_index(op.f('ix_room_transfers_room_id'), table_name='room_transfers')
    op.drop_table('room_transfers')
    op.drop_index(op.f('ix_orders_tenant_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_room_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_building_staff_institute_id'), table_name='building_staff')
    op.drop_table('building_staff')
    op.drop_index(op.f('ix_building_images_institute_id'), table_name='building_images')
    op.drop_index(op.f('ix_building_images_id'), table_name='building_images')
    op.drop_table('building_images')
    op.drop_table('tenants')
    # ### end Alembic commands ###
